name: bigboxx-lora
base: core18
version: git
summary: LoRa Gateway driver of middleware from e-Cattle platform for livestock farms
description: |
  e-Cattle BigBoxx is a middleware to receive, rank, segment, persist and provide sensory data
  for IoT applications in livetstock farms. This driver makes the interface with Radioenge LoRa Gateway shield.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

environment:
  SNAPCRAFT_ENABLE_DEVELOPER_DEBUG: "yes"

apps:
  forwarder:
    command: ./forwarder/lora_pkt_fwd/lora_pkt_fwd
    daemon: simple
    restart-condition: always

plugs:
  home:
  network:
  network-bind:
  spi:

parts:
  driver:
    source: https://github.com/Lora-net/lora_gateway.git
    plugin: make
    build-packages:
      - build-essential
    override-build: |
      make all
      cp -rf $SNAPCRAFT_PART_INSTALL/../build $SNAPCRAFT_PRIME/driver
  
  forwarder:
    source: https://github.com/Lora-net/packet_forwarder.git
    plugin: make
    after: [driver]
    build-packages:
      - build-essential
    override-build: |
      export LGW_PATH="$SNAPCRAFT_PART_INSTALL/../../driver/build/libloragw"
      make all
      cp -rf $SNAPCRAFT_PART_INSTALL/../build $SNAPCRAFT_PRIME/forwarder
